### ISSUE TITLE
h5py Error when converting CSV data to hdf5

### ISSUE THREAD

**Issue by kannan-sosaley** [antonior92/automatic-ecg-diagnosis#12]
I've 12-Lead ecg data recorded in csv format, i converted this csv to hdf5  as below

```
df = pandas.read_csv(file, delimiter=',', usecols=[0,1,2,3,4,5,6,7,8,9,10,11], skiprows=1,header=None)
df.to_hdf('ecg.hdf5', key='tracings', mode='w')
```
when i run the converted hdf5, to predict.py i get error 
```
  File "/home/pi/.local/lib/python3.7/site-packages/h5py/_hl/base.py", line 137, in _e
    name = name.encode('ascii')
AttributeError: 'tuple' object has no attribute 'encode'
```
am i going wrong anywhere? 
but works fine when i run sampleData.hdf5, i couldn't pass my csv data

**Comment by antonior92** [comment]
Hi Kannan, I am not sure... It seems the problem is with your call to pandas hdf interface

I usually use h5py directly to generate the file...

**Comment by kannan-sosaley** [comment]
Does this codebase has script for converting raw ecg data from csv to hdf5
Even using h5py for converting gives me some sort of errors
Could u share the snippet for convering csv to hdf5, i would be grateful for tat

**Comment by wb666greene** [comment]
Use Python built-in csv module
`    import csv
       with open(filepath, 'r', encoding="utf8") as f:
        reader = csv.reader(f, delimiter=',')
        headers = next(reader)
        data = np.array(list(reader)).astype(float)
    print(headers) # to verify columns are read correctly
    csvdata=data.transpose() 
`
You may or may not need the transpose depending on how you do things with the csvdata.

Wrtie to hdf5:
`
        import h5py
        # create hdf5 dataset
        hf = h5py.File(args.hdf5_name, 'w')
        d_set = hf.create_dataset('tracings', (Nekgfiles, 4096, 12), maxshape=(None, 4096, 12), dtype='f')
        id_set = hf.create_dataset('exam_id', (Nekgfiles, ), maxshape=(None, ), 
        dtype=h5py.string_dtype(encoding='utf-8' ) )

        # write record
        id_set[index] = nameStr  # build list of patientIDs
        d_set[index, :, :] = ecg400.transpose()
`
Again, you may or may not need the transpose.
I apologize in advance but github markdown is awful for sharing code snippits.
