### ISSUE TITLE
Database format

### ISSUE THREAD

**Issue by IgnacioPizarro** [antonior92/automatic-ecg-diagnosis#3]
Dear Antonio, 

First, I hope that you're fine in this difficult times. 

I have a dataset with functional data (float type) and I would like to know if it's possible to run the train code (train.py) with that type of data. I was watching your dataset and I saw that's binarized. 

I think that your data in first instance doesn't have the binary form that has now. Then, I would like to know How do you transform your data to binary? And How was the original type/form of your data?  

If you prefer mantain the privacity of your dataset, you can send me an email with your answer to epizarro@miuandes.cl. 

I appreciate your help for academic purposes. Best Regards. 

Ignacio Pizarro G.

**Comment by antonior92** [comment]
Hi Ignazio, the model should work in other datasets. You just need to pay attention to the following points:
1. The ECGs need to be sampled at 400 Hz;
2. All signals must have 4096 samples (~10 seconds), you can fill smaller signals with zeros..
3. All signals must have the scale adjusted to 1e-4V
For instance if you had the samples save in a string format you could use something similar to this:
```
def resample_ecg(trace, input_freq, output_freq=500):
    trace = np.atleast_1d(trace).astype(float)
    if input_freq != int(input_freq):
        raise ValueError("input_freq must be an integer")
    if output_freq != int(output_freq):
        raise ValueError("output_freq must be an integer")

    if input_freq == output_freq:
        new_trace = trace
    elif np.mod(input_freq, output_freq) == 0:
        new_trace = decimate(trace, q=input_freq//output_freq,
                             ftype='iir', zero_phase=True)
    else:
        new_trace = resample_poly(trace, up=output_freq, down=input_freq)
    return new_trace


def resize_to(x, new_length):
    x_new = np.zeros(new_length)
    length = np.shape(x)[0]
    if length >= new_length:
        extra = (length - new_length) // 2
        x_new = x[extra:new_length+extra]
    else:
        pad = (new_length - length) // 2
        x_new[pad:length+pad] = x
    return x_new


def convert_to_ndarray(string):
    elements = string.split(";")[:-1]
    ecg_samples = [int(x) for x in elements]
    return np.array(ecg_samples, dtype=np.float32)/512


def generate_signal(samples, gain, sensibility, sample_rate, n_samples=4096, final_sample_rate=400):
    x = convert_to_ndarray(samples)  # Convert string to Array
    x = x / gain * sensibility
    x = resample_ecg(x, sample_rate, final_sample_rate)  # Convert to 400 Hz
    x = resize_to(x, n_samples)  # Resize array
    x = 10 * x  # Rescale (Use 10 mV scale instead of 1mV scale)
    return x
```

As the code is now, you need to convert the data to hdf5 format. You can use for instance h5py to do that: https://www.h5py.org/.  Also, make sure your ECG leads are ordered in the right order inside the tensor you save in hdf5:  {DI, DII, DIII, AVL, AVF, AVR, V1, V2, V3, V4, V5, V6}.

One possible sanity check is to compare what you generate with: https://zenodo.org/record/3765780#.Xrvf5xNKhhE.

**Comment by IgnacioPizarro** [comment]
Hi, 

Thanks a lot, Antonio. My functions are based in human gait data, but I don’t have a large data :( It’s very poor in that sense. I hope your model can help me. I’ll probe both links, thank you! 

Ignacio P.

**Comment by guijuzhejiang** [comment]
I checked the code here: x = 10 * x # Rescale (Use 10 mV scale instead of 1mV scale). 
It contradicts with what you said "All signals must have the scale adjusted to 1e-4V".
Do you mean All signals must have the scale adjusted to 1e-2V.
Or am I understanding it wrong?

**Comment by guijuzhejiang** [comment]
Thank you very much for your work.I don't know how to determine the parameters gain and sensibility in the generate_signal method?Can you tell me the answer.Thanks.

**Comment by antonior92** [comment]
In our case, these parameters were saved in the XML file and would scale the ECG.  Depending on how your data is stored, it might be slightly different...

I would not worry too much about these parameters. Just make sure your ECG is scaled as millivolts...

**Comment by huqingtao2018** [comment]
Dear Antonio,

Thank you for your work. I have no idea how to format my XML ECG file, as there are no gain/sensibility parameters. Would you please share one or two example XML file to me (from the 827 test data), which will do me a great favour.

**Comment by masterchen** [comment]
@huqingtao2018  Hi , i also have the same questions, did you get the proper raw ecg file ?

**Comment by huqingtao2018** [comment]
@masterchen Hi, I got the proper raw ecg file. Whether you can get proper raw ecg file totally depends on the file format exported by the ECG machine. From my experience, hl7 format can easily be used as there is scale factor within that file.

**Comment by masterchen** [comment]
@huqingtao2018   well done ! can you please share one of the files  for me as an example ? i have many kinds of ECG machine,  which are form philip and mindray .  scale souns good idea , but if the sample rate of the  ecg signal  is not 400Hz, how to deal with it ?  whether we can change some  depp learning  code to math the sample rate ?

**Comment by antonior92** [comment]
Hi @masterchen, the code above does the resampling by using the scipy function [`resample_poly`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.resample_poly.html) to deal with this possibility. 

```
new_trace = resample_poly(trace, up=output_freq, down=input_freq)
```

**Comment by antonior92** [comment]
> can you please share one of the files for me as an example ? 
Sorry, the source files contain de-anonymized information and cannot be shared...

**Comment by masterchen** [comment]
> Hi @masterchen, the code above does the resampling by using the scipy function [`resample_poly`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.resample_poly.html) to deal with this possibility.
> 
> ```
> new_trace = resample_poly(trace, up=output_freq, down=input_freq)
> ```

Thank you for your guidence, hlep me a lot !
