### ISSUE TITLE
request for the full ecg dataset

### ISSUE THREAD

**Issue by rdyan0053** [antonior92/automatic-ecg-diagnosis#31]
Hi,
I use the Monash student email to request the full CODE dataset: [[doi: 10.17044/scilifelab.15169716](https://doi.org/10.17044/scilifelab.15169716)](https://doi.org/10.17044/scilifelab.15169716).

However, I encountered such a problem when I log in this site to request the dataset：
![image](https://github.com/antonior92/automatic-ecg-diagnosis/assets/53009617/1270f3b8-deba-432e-b16b-1c9458ada921)

Could you share the dataset by other tools? Google Drive or Baidu Drive. Thank  you!!!

**Comment by antonior92** [comment]
The link seems to be working for me. I don't understand where you get this error page

**Comment by antonior92** [comment]
Requests should be made by mail, or using the request box on the figshare. You don't need to login
